DO $$
DECLARE
  base_url TEXT := 'https://mcwthjcpcajhvhwpuvvs.supabase.co/storage/v1/object/public/product-images/products/';
BEGIN
UPDATE products SET image_url = base_url || 'blood-detox-main.webp', additional_images = ARRAY[base_url || 'blood-detox-alt-1.webp', base_url || 'blood-detox-alt-2.webp'] WHERE slug = 'blood-detox';
UPDATE products SET image_url = base_url || 'blue-vervain-main.webp', additional_images = ARRAY[base_url || 'blue-vervain-alt-1.webp', base_url || 'blue-vervain-alt-2.webp'] WHERE slug = 'blue-vervain';
UPDATE products SET image_url = base_url || 'blue-vervaine-main.webp', additional_images = ARRAY[base_url || 'blue-vervaine-alt-1.webp', base_url || 'blue-vervaine-alt-2.webp'] WHERE slug = 'blue-vervaine';
UPDATE products SET image_url = base_url || 'bay-leaf-laurus-nobilis-main.webp', additional_images = ARRAY[base_url || 'bay-leaf-laurus-nobilis-alt-1.webp', base_url || 'bay-leaf-laurus-nobilis-alt-2.webp'] WHERE slug = 'bulk-bay-leaf-laurus-nobilis';
UPDATE products SET image_url = base_url || 'bulk-cassia-alata-king-of-the-forest-main.webp', additional_images = ARRAY[base_url || 'bulk-cassia-alata-king-of-the-forest-alt-1.webp'] WHERE slug = 'bulk-cassia-alata-king-of-the-forest';
UPDATE products SET image_url = base_url || 'gully-root-anamu-leaves-petiveria-alliacea-main.webp', additional_images = ARRAY[base_url || 'gully-root-anamu-leaves-petiveria-alliacea-alt-1.webp'] WHERE slug = 'bulk-gully-root-anamu-leaves';
UPDATE products SET image_url = base_url || 'gully-root-anamu-roots-petiveria-alliacea-main.webp', additional_images = ARRAY[base_url || 'gully-root-anamu-roots-petiveria-alliacea-alt-1.webp'] WHERE slug = 'bulk-gully-root-anamu-roots';
UPDATE products SET image_url = base_url || 'red-raspberry-leaf-rubus-idaeus-main.webp', additional_images = ARRAY[base_url || 'red-raspberry-leaf-rubus-idaeus-alt-1.webp'] WHERE slug = 'bulk-red-raspberry-leaf-rubus-idaeus';
UPDATE products SET image_url = base_url || 'st-john-s-bush-justicia-secunda-main.webp', additional_images = ARRAY[base_url || 'st-john-s-bush-justicia-secunda-alt-1.webp'] WHERE slug = 'bulk-st-johns-bush-justicia-secunda';
UPDATE products SET image_url = base_url || 'cassia-alata-main.webp', additional_images = ARRAY[base_url || 'cassia-alata-alt-1.webp', base_url || 'cassia-alata-alt-2.webp'] WHERE slug = 'cassia-alata';
UPDATE products SET image_url = base_url || 'colax-main.webp', additional_images = ARRAY[base_url || 'colax-alt-1.webp', base_url || 'colax-alt-2.webp', base_url || 'colax-alt-3.webp'] WHERE slug = 'colax';
UPDATE products SET image_url = base_url || 'dewormer-main.webp', additional_images = ARRAY[base_url || 'dewormer-alt-1.webp', base_url || 'dewormer-alt-2.webp'] WHERE slug = 'dewormer';
UPDATE products SET image_url = base_url || 'digestive-bundle-main.webp', additional_images = NULL WHERE slug = 'digestive-bundle';
UPDATE products SET image_url = base_url || 'digestive-rescue-main.webp', additional_images = ARRAY[base_url || 'digestive-rescue-alt-1.webp'] WHERE slug = 'digestive-rescue';
UPDATE products SET image_url = base_url || 'feminine-balance-kit-main.webp', additional_images = NULL WHERE slug = 'feminine-balance-kit';
UPDATE products SET image_url = base_url || 'fertility-main.webp', additional_images = ARRAY[base_url || 'fertility-alt-1.webp', base_url || 'fertility-alt-2.webp', base_url || 'fertility-alt-3.webp'] WHERE slug = 'fertility';
UPDATE products SET image_url = base_url || 'fey-duvan-syrup-main.webp', additional_images = ARRAY[base_url || 'fey-duvan-syrup-alt-1.webp', base_url || 'fey-duvan-syrup-alt-2.webp', base_url || 'fey-duvan-syrup-alt-3.webp'] WHERE slug = 'fey-duvan-syrup';
UPDATE products SET image_url = base_url || 'free-flow-main.webp', additional_images = ARRAY[base_url || 'free-flow-alt-1.webp', base_url || 'free-flow-alt-2.webp'] WHERE slug = 'free-flow';
UPDATE products SET image_url = base_url || 'gully-root-leaves-main.webp', additional_images = ARRAY[base_url || 'gully-root-leaves-alt-1.webp', base_url || 'gully-root-leaves-alt-2.webp'] WHERE slug = 'gully-root-leaves';
UPDATE products SET image_url = base_url || 'handcrafted-seamoss-soaps-3-pack-main.webp', additional_images = ARRAY[base_url || 'handcrafted-seamoss-soaps-3-pack-alt-1.webp', base_url || 'handcrafted-seamoss-soaps-3-pack-alt-2.webp', base_url || 'handcrafted-seamoss-soaps-3-pack-alt-3.webp'] WHERE slug = 'handcrafted-seamoss-soaps-3-pack';
UPDATE products SET image_url = base_url || 'hemp-syrup-main.webp', additional_images = ARRAY[base_url || 'hemp-syrup-alt-1.webp'] WHERE slug = 'hemp-syrup';
UPDATE products SET image_url = base_url || 'immunity-kit-bundle-main.webp', additional_images = ARRAY[base_url || 'immunity-kit-bundle-alt-1.webp', base_url || 'immunity-kit-bundle-alt-2.webp'] WHERE slug = 'immunity-kit-bundle';
UPDATE products SET image_url = base_url || 'kingly-tea-bundle-main.webp', additional_images = ARRAY[base_url || 'kingly-tea-bundle-alt-1.webp'] WHERE slug = 'kingly-tea-bundle';
UPDATE products SET image_url = base_url || 'male-potency-kit-main.webp', additional_images = ARRAY[base_url || 'male-potency-kit-alt-1.webp', base_url || 'male-potency-kit-alt-2.webp'] WHERE slug = 'male-potency-kit';
UPDATE products SET image_url = base_url || 'male-potency-kit-bundle-main.webp', additional_images = ARRAY[base_url || 'male-potency-kit-bundle-alt-1.webp'] WHERE slug = 'male-potency-kit-bundle';
UPDATE products SET image_url = base_url || 'male-vitality-package-main.webp', additional_images = NULL WHERE slug = 'male-vitality-package';
UPDATE products SET image_url = base_url || 'medina-tea-main.webp', additional_images = ARRAY[base_url || 'medina-tea-alt-1.webp', base_url || 'medina-tea-alt-2.webp'] WHERE slug = 'medina-tea';
UPDATE products SET image_url = base_url || 'moon-cycle-tea-main.webp', additional_images = ARRAY[base_url || 'moon-cycle-tea-alt-1.webp', base_url || 'moon-cycle-tea-alt-2.webp', base_url || 'moon-cycle-tea-alt-3.webp'] WHERE slug = 'moon-cycle-tea';
UPDATE products SET image_url = base_url || 'nerve-tonic-capsules-main.webp', additional_images = ARRAY[base_url || 'nerve-tonic-capsules-alt-1.webp'] WHERE slug = 'nerve-tonic-capsules';
UPDATE products SET image_url = base_url || 'patchouli-main.webp', additional_images = ARRAY[base_url || 'patchouli-alt-1.webp'] WHERE slug = 'patchouli';
UPDATE products SET image_url = base_url || 'prosperity-main.webp', additional_images = ARRAY[base_url || 'prosperity-alt-1.webp'] WHERE slug = 'prosperity';
UPDATE products SET image_url = base_url || 'prostate-health-bundle-main.webp', additional_images = NULL WHERE slug = 'prostate-health-bundle';
UPDATE products SET image_url = base_url || 'pure-gold-main.webp', additional_images = ARRAY[base_url || 'pure-gold-alt-1.webp'] WHERE slug = 'pure-gold';
UPDATE products SET image_url = base_url || 'pure-green-main.webp', additional_images = ARRAY[base_url || 'pure-green-alt-1.webp', base_url || 'pure-green-alt-2.webp'] WHERE slug = 'pure-green';
UPDATE products SET image_url = base_url || 'red-raspberry-leaf-main.webp', additional_images = ARRAY[base_url || 'red-raspberry-leaf-alt-1.webp', base_url || 'red-raspberry-leaf-alt-2.webp'] WHERE slug = 'red-raspberry-leaf';
UPDATE products SET image_url = base_url || 'restful-tea-main.webp', additional_images = ARRAY[base_url || 'restful-tea-alt-1.webp', base_url || 'restful-tea-alt-2.webp'] WHERE slug = 'restful-tea';
UPDATE products SET image_url = base_url || 'soursop-leaves-main.webp', additional_images = ARRAY[base_url || 'soursop-leaves-alt-1.webp', base_url || 'soursop-leaves-alt-2.webp'] WHERE slug = 'soursop-leaves';
UPDATE products SET image_url = base_url || 'st-john-bush-justicia-secunda-main.webp', additional_images = ARRAY[base_url || 'st-john-bush-justicia-secunda-alt-1.webp', base_url || 'st-john-bush-justicia-secunda-alt-2.webp'] WHERE slug = 'st-john-bush-justicia-secunda';
UPDATE products SET image_url = base_url || 'st-john-s-bush-main.webp', additional_images = ARRAY[base_url || 'st-john-s-bush-alt-1.webp', base_url || 'st-john-s-bush-alt-2.webp'] WHERE slug = 'st-johns-bush';
UPDATE products SET image_url = base_url || 'super-female-wellness-package-main.webp', additional_images = ARRAY[base_url || 'super-female-wellness-package-alt-1.webp', base_url || 'super-female-wellness-package-alt-2.webp', base_url || 'super-female-wellness-package-alt-3.webp'] WHERE slug = 'super-female-wellness-package';
UPDATE products SET image_url = base_url || 'the-answer-main.webp', additional_images = ARRAY[base_url || 'the-answer-alt-1.webp', base_url || 'the-answer-alt-2.webp'] WHERE slug = 'the-answer';
UPDATE products SET image_url = base_url || 'the-new-herbal-manual-ebook-main.webp', additional_images = NULL WHERE slug = 'the-new-herbal-manual-ebook';
UPDATE products SET image_url = base_url || 'the-new-herbal-manual-physical-copy-main.webp', additional_images = NULL WHERE slug = 'the-new-herbal-manual-physical';
UPDATE products SET image_url = base_url || 'tranquility-main.webp', additional_images = ARRAY[base_url || 'tranquility-alt-1.webp', base_url || 'tranquility-alt-2.webp'] WHERE slug = 'tranquility';
UPDATE products SET image_url = base_url || 'urinary-cleanse-tea-main.webp', additional_images = ARRAY[base_url || 'urinary-cleanse-tea-alt-1.webp', base_url || 'urinary-cleanse-tea-alt-2.webp'] WHERE slug = 'urinary-cleanse-tea';
UPDATE products SET image_url = base_url || 'virili-tea-main.webp', additional_images = ARRAY[base_url || 'virili-tea-alt-1.webp'] WHERE slug = 'virili-tea';
UPDATE products SET image_url = base_url || 'virility-main.webp', additional_images = ARRAY[base_url || 'virility-alt-1.webp'] WHERE slug = 'virility-herbal-virility-supplement';
UPDATE products SET image_url = base_url || 'virility-male-balance-capsules-main.webp', additional_images = ARRAY[base_url || 'virility-male-balance-capsules-alt-1.webp', base_url || 'virility-male-balance-capsules-alt-2.webp'] WHERE slug = 'virility-male-balance-capsules';
END $$;